### PR TITLE
 ASM-7709 puppet/ntp issue patch

### PR DESCRIPTION
**Pull request by ksw2599**
This commit addresses the issue where the ntp service interferes
with the puppet-agent process on the Windows 2008 and 2012. When
the interference occurs, the puppet-agent is stuck indefinitely
until the system time catches up to new time set by the ntp service.
This typically takes a few hours to sync, so the deployment times
out and fails.

In order to resolve this issue, default-unattended.xml.erb files for
the Windows 2008 and 2012 are updated. The RunSynchronous commands
are rearranged to configure the ntp service before installing and
configuring the puppet service. Additionally, the ntp service is
set to start up at the system startup while the puppet service is
set to start after other system services (including the ntp) to
reduce the possibility of the interference.

The validation results show that this removed the deployment fail-
ures from the environment where ntp/puppet conflicts could be seen
for every deployment. Also deploying the Windows VM's without the
ntp server(s) also function correctly.

### CODE REVIEW

**Comment by ripienaar** [comment]
needs a commit message, PR title isn't in the correct format - we dont say what releases PRs or commits are for

**Comment by ksw2599** [comment]
@ripienaar: the commit has been updated. Let me know if this looks better

**Comment by ripienaar** [comment]
@ksw2599 we prefer a more paragraph based approach to commit message, see for example the example from @gavin-scott here https://github.com/dell-asm/asm-deployer/pull/1894#issuecomment-249250300

**Comment by aimers1975** [comment]
@ksw2599 Have you addressed all the feedback here?

**Comment by ksw2599** [comment]
@ripienaar, @aimers1975: I had to address another validation case that @sushilrai pointed out in https://github.com/dell-asm/razor-server/pull/114. Now the commit message is updated as paragraphs.

**Comment by ripienaar** [comment]
very good commit thanks @ksw2599, unfortunately I don't know what all this does so for functionality review someone else must merge

**Comment by ksw2599** [comment]
@ripienaar: Functionally this is the backported version of https://github.com/dell-asm/razor-server/pull/114. @gavin-scott, @sushilrai: Can you merge this one as well when you merge https://github.com/dell-asm/razor-server/pull/114?

**Comment by gavin-scott** [comment]
I'm not positive what the expectation is w.r.t. 8.2.1 patch. Let me follow up with deployment team before we merge this.

**Comment by gavin-scott** [comment]
This is way out of date, we're clearly not merging anything into 8.2 at this stage...

**Pull request closed without merging**
