### PR TITLE
ASM-7011 Update NTP configuration for HyperV server during initial installation

### PR DESCRIPTION
**Pull request by sushilrai**
Update the NTP configuration on the server as part of OS installation so that puppet check-in happens with correct time configuration.

### CODE REVIEW

**Comment by gavin-scott** [comment]
Looks like we need this in windows2008 task as well: https://github.com/dell-asm/razor-server/blob/master/tasks/windows2008.task/hyper-v-unattended.xml.erb

**Comment by gavin-scott** [comment]
Ping.

**Comment by gavin-scott** [comment]
@sushilrai please update windows2008 task

**Comment by sushilrai** [comment]
@gavin-scott  I missed the update on this PR. We do not support HyperV installation with Windows 2008 / R2. Our post-installation is not compatible with 2008 thats why I havent updated the post-installation file.

**Comment by gavin-scott** [comment]
Ah, makes sense. OK

**Pull request merged**
